### PR TITLE
updated installation page

### PR DESCRIPTION
**Pull request by Beafantles**
I updated the installation page to use the new installers.

What might get improved:

- convert .gif to .webp
- some optimizations with resources

### CODE REVIEW

**Review by kristype — APPROVED** [review]
Looks good. Just some minor stuff.

- The spacing for the H3 headers does not fit with the rest of the site.
- Sematically H3 should follow H2 so screen readers understand the content.
- We could add loading="lazy" on the images under the fold, or just on all images for this page, since the fold will be high on mobile for example.

If you want to convert the gifs to webp, you could just use the command in the README file.

Everything works on my end :)

**Comment by kristype** [comment]
One more thing, the last P tag should be placed in a `<section class="content" >` to get the correct padding

**Comment by kristype** [comment]
Image scaling on mobile is broken with the changes you made to `.content-image`. I think you should make a new class if you want to limit the size of certain pictures. The max-widht: 720px was made so it matches the youtube thumbnail width.

**Review by kristype — CHANGES_REQUESTED** [review]
Image scaling on mobile is broken with the changes you made to `.content-image`. I think you should make a new class if you want to limit the size of certain pictures. The max-widht: 720px was made so it matches the youtube thumbnail width.

**Comment by Beafantles** [comment]
Alright, thank you very much for the review Kris. Here's some changes I've made:

- I used h2 instead of h3.
- Added lazy loading for the images
- converted every images (gif / png) to webp
- added a new `section` tag for the last paragraph
- reverted changes on the `content-image` class (layout file) so the image scaling on mobile still works.

**Comment by Beafantles** [comment]
I believe this should be good now :D

**Review by kristype — APPROVED** [review]
Yup, LGTM :)

**Pull request merged**
